### ISSUE TITLE
랜딩페이지 디자인 수정

### ISSUE THREAD

**Issue by chanwukim** [oduck-team/oduck-client#147]
## ✅ TODO
- [x] 애니 랭킹 애니메이션 카드 좌우로 뚫리게 슬라이드
- [x] 애니 카드들 좌우로 뚫리게 슬라이드
- [x] 문서 구조를 더 시맨틱하게
