### ISSUE TITLE
디자인 변경사항 2

### ISSUE THREAD

**Issue by chanwukim** [oduck-team/oduck-client#201]
## ✅ TODO
- [x] 애니 상세 페이지 중단 별점 간격
- [ ] 검색 페이지 - 타이핑 검색후 취소 나오게 수정
- [ ] 애니 검색시 애니 카드 Width 100%
- [x] 한 줄 리뷰 모달 `포인트` 색 primary로
- [x] 입덕 포인트의 체크 박스 height 32 -> 40
- [x] 공지사항 리스트 페이지 - ios에서 arrow 색 파랑으로 보임
- [x] 검색 페이지 검색바 아이폰 글자 크기
- [x] 바텀 시트 핸들바의 움직임 개선
- [x] 애니 리스트 헤더와 컨텐츠간 간격
- [x] 입덕포인트간 간격
- [x] 총 N명이 리뷰를 남겨 주셨어요 fontsize
- [x] 총 N명이 리뷰를 남겨 주셨어요 , 하단 칩 간격 16으로
- [x] 한 줄 리뷰 위아래 border 1px로
