### ISSUE TITLE
스타일 변경사항을 반영한다.

### ISSUE THREAD

**Issue by presentKey** [oduck-team/oduck-client#225]
## 📝 개요
스타일 변경사항을 반영한다.

## ✅ TODO
- [x] root height 제한 없애기
- [x] 프로필 페이지 정렬 버튼 ios 색상 변경
- [x] ShortReviewModal 높이 제한
