### ISSUE TITLE
애니 상세 페이지 - 애니 상세 조회 API 응답 바인딩

### ISSUE THREAD

**Issue by chanwukim** [oduck-team/oduck-client#237]
## ✅ TODO
- [x] 애니 API 응답을 애니 상세 페이지에 바인딩
- [x] api 수정 반영하기
- [x] 줄거리 섹션 간격 수정
