### ISSUE TITLE
프로필 수정 버그를 수정한다.

### ISSUE THREAD

**Issue by presentKey** [oduck-team/oduck-client#326]
## 📝 개요
프로필 수정 버그를 수정한다.

## ✅ TODO
- [x] 자기소개 변경 후, 다시 수정 페이지오면 반영되어 있지 않음
- [x] 한글 자음으로 닉네임을 채우면, 기존 닉네임으로 초기화
- [x] 닉네임 중복 토스트 UI 추가
