### ISSUE TITLE
메인 페이지 변경사항을 반영한다.

### ISSUE THREAD

**Issue by presentKey** [oduck-team/oduck-client#333]
## 📝 개요
메인 페이지 변경사항을 반영한다.

## ✅ TODO
- [x] 최상단 캐러셀 → 캐러셀 제거
- [x] 신작애니, 이번주 TOP10 위치 변경
- [x] 폰트 스타일 변경
