### ISSUE TITLE
애니 상세페이지 스타일 추가 적용

### ISSUE THREAD

**Issue by imdaxsz** [oduck-team/oduck-client#338]
## 📝 개요

애니 상세페이지 스타일 추가 적용

## ✅ TODO
- [ ] 스켈레톤 적용
- [x] 내 리뷰 영역 퍼블리싱
- [x] 줄거리 더보기/접기 추가
- [x] 스타일 변경 사항 적용
