### ISSUE TITLE
fix: 프로필 수정페이지 버그 및 개선

### ISSUE THREAD

**Issue by presentKey** [oduck-team/oduck-client#354]
## 📝 개요
프로필 수정페이지 버그 및 개선

## ✅ TODO
- [x] Avatar컴포넌트의 default username 변경
- [x] form sumbit 이벤트에 useDebounce hook 적용 시, 엔터를 누르면 페이지가 새로고침되는 현상 수정
- [x] 닉네임 정규식 검사 시점 추가
