### ISSUE TITLE
디자인 변경 사항

### ISSUE THREAD

**Issue by a-ryang** [oduck-team/oduck-client#97]
## 📝 개요
- figma 디자인 변경 사항
- 디스코드 내용 업데이트중
## ✅ TODO
- [x] Stat 쉐도우
- [x] 애니 리스트 filter (Bottom Sheet) 간격, 크기, 타이포 등
- [x] Chip select primary 60, border primary 50, default netural 50 border neutral 20
- [x] BottomNavigation icons
- [x] 탭 메뉴 간격 조정
- [ ] 애니 상세 페이지 중단 별점 간격
- [x] 랜딩 페이지 구분라인 마진 0에서 16으로 수정
- [x] 랜딩 페이지 라인과 리뷰내용 사이 간격 24에서 16으로 수정
- [ ] 검색 페이지 - 타이핑 검색후 취소 나오게 수정
- [x] 랜딩 배너 안의 이미지 좌우 마진 추가하기
- [x] header height 60px
- [x] 랜딩 배너 카드 안에서 이미지가 슬라이드 x -> 카드들이 슬라이드
- [x] 이번주 TOP 10 좌우 애니 슬라이드시 좌우 패딩 사라져야함
- [ ] 애니 검색시 애니 카드 Width 100%

**Comment by chanwukim** [comment]
#201 로 이동
